package by.htp.ex.controller.command;

public enum CommandName {
	GO_TO_BASE_PAGE, 
	GO_TO_LOGINATION_PAGE, 
	GO_TO_REGISTRATION_PAGE_COMMAND,
	GO_TO_ADD_NEWS,
	GO_TO_NEWS_LIST, 
	GO_TO_VIEW_NEWS,
	GO_TO_EDIT_NEWS,
	GO_TO_ERROR_PAGE,
	DO_SIGN_IN, 
	DO_SIGN_OUT,
	DO_REGISTRATION,
	DO_ADD_NEWS,
	DO_EDIT_NEWS,
	DO_DELETE_NEWS,
	CHANGE_LOCALE
}
