newsid_news-- MySQL Script generated by MySQL Workbench
-- Wed Mar  1 10:17:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema goodNews
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema goodNews
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `goodNews` DEFAULT CHARACTER SET utf8 ;
USE `goodNews` ;

-- -----------------------------------------------------
-- Table `goodNews`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goodNews`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodNews`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goodNews`.`news` (
  `id_news` INT NOT NULL AUTO_INCREMENT,
  `title` MEDIUMTEXT NOT NULL,
  `brief_news` MEDIUMTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_news`),
  CONSTRAINT `user`
    FOREIGN KEY (`id_news`)
    REFERENCES `goodNews`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
