-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 21:30:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema goodNews
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema goodNews
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `goodNews` DEFAULT CHARACTER SET utf8 ;
USE `goodNews` ;

-- -----------------------------------------------------
-- Table `goodNews`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goodNews`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodNews`.`news_site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goodNews`.`news_site` (
  `news_id` INT NOT NULL AUTO_INCREMENT,
  `title` MEDIUMTEXT NOT NULL,
  `brief` MEDIUMTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `user_id` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`news_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
